Add support for IJON
fuzzuf/fuzzuf pull request #74
Opened 2022-06-06 11:01 UTC by Fadis

IJON instrumented executable records 3 kind of values on shared memory. First is traditional AFL coverage. Second is "IJON counter" which records how many times IJON_INC is called at the place. Third is "IJON max" which records the highest value passed to IJON_MAX at the place.
Yet original IJON implementation uses struct to place 3 arrays on one shared memory, this prevents support for variable length AFL coverage.
To support variable length AFL coverage in future, fuzzuf tells each array sizes to PUT by environment variables instead.
In original IJON implementation, AFL coverage and IJON counter is recorded in same array. Since collisions of AFL coverage is considered to decrease AFL performance, this   sharing make situation worse.
To avoid this problem, fuzzuf implementation split AFL coverage and IJON counter in different arrays.

All three arrays are concatenated and passed to traditional AFL feedback. To achieve this without copy data, three arrays should placed on same shared memory.
This is why the implementation split one large shared memory instead to create three independent shared memories.

Due to the difference above, the test PUT must be built using fuzzuf-cc.
If fuzzuf-cc is not installed on the system, corresponding tests will be skipped.

## Type of PR

- [ ] Changes related to the roadmap (e.g., TODO.md) (type: A) -> Create an issue corresponding to the PR in advance, and refer to this PR in the issue.
- Changes that are not related to the roadmap
    - [ ] Change with multiple possible solutions to the issue (type: B-1) -> Create an issue corresponding to the PR in advance and refer to this PR in the issue.
    - [x] Change with a single solution (type: B-2) -> There is no need to create an issue corresponding to the PR in advance. Please discuss it in this PR.

## Related Issue

## Importance of PR

- Importance of the issue
    - [ ] Large (based on several days to weeks of discussion and verification, e.g., this issue is a blocking issue for other issues on the roadmap, etc.)
    - [x] Medium (based on a few hours to a day of discussion and verification, e.g., this issue is a blocking issue for another minor issue)
    - [ ] Small (apparent changes such as build error)
- Complexity of the solution (code, tests, etc.)
    - [ ] Large (requires several days to several weeks of review)
    - [x] Medium (requires several hours to a day of review)
    - [ ] Small (trivial changes, such as build error)

## PR Overview

## Concerns (Optional)

- [ ] Performance
- [ ] Source Code Quality

---

> The PR author should fill in the following checklist when submitting this PR.

#### Optional Entries
- [ ] If this PR is a PR type A/B-1, there is a cross-link between this PR and the related issue.

#### Mandatory Entries
- [ ] The PR title is a summary of the changes.
- [ ] Completed each required field of the PR.

---
> The PR author should fill out the following checklist in the comments to confirm that this PR is ready to be merged

- [ ] CI is green or confirmed test run results.
- [ ] All change suggestions from reviewers have been resolved (fixed or foregone).

---
> The maintainer of this repository will set up a reviewer for each PR.
> PR reviewers should review this PR in terms of the checklist below before moving on to a detailed code review. Please comment on their initial response by filling in the checklist below.

#### Optional Entries
- [ ] The reviewer assigned more reviewers if needed.
- [ ] The reviewer noted that it is necessary to break out some of the changes in this PR into other PRs if needed.
- [ ] The reviewer noted that the initial response is insufficient if needed.

#### Mandatory Entries
- [ ] The title of this PR summarizes the changes made by this PR properly.
- [ ] The target branch of this PR is as intended.
- [ ] The reviewer understands the issues in this PR.
- [ ] The reviewer plans to review with an appropriate workload based on the importance of this PR.

---
> When the PR reviewer concludes that this PR is ready to be merged, please fill in the checklist below by posting it in the comment. If there is more than one reviewer, please do this on your own.

#### Optional Entries
- [ ] The reviewer noted that if you believe that new tests are needed to evaluate this PR, they have been noted.
- [ ] If minor refactorings are not mentioned in the PR, I understand the intent.
- [ ] If this PR is a PR type A/B-1, we have agreed on this PR's design, direction, and granularity in the related issue.

#### Mandatory Entries
- [ ] The reviewer understands how this PR addresses the issue and the specific changes.
- [ ] This PR uses the best possible issue resolution that the reviewer can think of.
- [ ] This PR is ready to be merged.

2022-06-09 06:13 UTC, mkYYY requested changes
#### Mandatory Entries
- [x] The title of this PR summarizes the changes made by this PR properly.
- [x] The target branch of this PR is as intended.
- [x] The reviewer understands the issues in this PR.
- [x] The reviewer plans to review with an appropriate workload based on the importance of this PR.

---

I agree with the changes made in this branch to use three different regions in the shared memory. 
In addition to the review comments, did you intentionally add `.gitmodules` file?

2022-06-09 06:13 UTC, mkYYY commented on executor/linux_fork_server_executor.cpp
> +//) : LinuxForkServerExecutor( std::move( args ) ) {}
Do we still need this commented-out constructor?

2022-06-09 06:13 UTC, mkYYY commented on include/fuzzuf/executor/linux_fork_server_executor.hpp
> +  LinuxForkServerExecutorParameters &
Any reason to return `LinuxForkServerExecutorParameter &` (any future usage plan)?

2022-06-09 06:13 UTC, mkYYY commented on docs/algorithms/ijon/manual.md
> +PUT must be computed using fuzzuf-ijon-cc that is provided by separated fuzzuf-cc repository.
possible typo here
```suggestion
PUT must be compiled using fuzzuf-ijon-cc that is provided by separated fuzzuf-cc repository.
```

2022-06-09 06:13 UTC, mkYYY commented on include/fuzzuf/algorithms/ijon/shared_data.hpp
> +};*/
The content of this header file is now empty. Shall we delete the file itself?

2022-06-09 06:13 UTC, mkYYY commented on include/fuzzuf/cli/fuzzer/ijon/build_ijon_fuzzer_from_args.hpp
> +#include "fuzzuf/algorithms/ijon/shared_data.hpp"
I believe this inclusion (at line 29) can safely be removed since `shared_data.hpp` is now empty

2022-06-09 06:13 UTC, mkYYY commented on include/fuzzuf/executor/ijon_executor_interface.hpp
> +  /// @returnIJON feedback.
missing whitespace?
```suggestion
  /// @return IJON feedback.
```

2022-06-09 06:13 UTC, mkYYY commented on cmake/FindFuzzufCC.cmake
> +  find_program( FUZZUF_CC_AFL_CXX fuzzuf-afl-c++ NO_DEFAULT_PATH PATHS ${FUZZUF_CC_ROOT}/ ${FUZZUF_CC_ROOT}/bin/ )
Due to this typo, `FUZZUF_CC_AFL_CXX` becomes NOT_FOUND, thus IJON PUTs are not going to be compiled and their tests are not run (though `fuzzuf-afl-cc++` is not actually required here)
```suggestion
  find_program( FUZZUF_CC_AFL_CXX fuzzuf-afl-cc++ NO_DEFAULT_PATH PATHS ${FUZZUF_CC_ROOT}/ ${FUZZUF_CC_ROOT}/bin/ )
```

2022-06-09 07:50 UTC, Fadis commented on include/fuzzuf/executor/linux_fork_server_executor.hpp
> +  LinuxForkServerExecutorParameters &
This is needed to call this function during "this" refers rvalue.

2022-06-09 08:32 UTC, Fadis commented on executor/linux_fork_server_executor.cpp
> +//) : LinuxForkServerExecutor( std::move( args ) ) {}
fixed

2022-06-09 08:32 UTC, Fadis commented on docs/algorithms/ijon/manual.md
> +PUT must be computed using fuzzuf-ijon-cc that is provided by separated fuzzuf-cc repository.
fixed

2022-06-09 08:32 UTC, Fadis commented on include/fuzzuf/algorithms/ijon/shared_data.hpp
> +};*/
fixed

2022-06-09 08:32 UTC, Fadis commented on include/fuzzuf/cli/fuzzer/ijon/build_ijon_fuzzer_from_args.hpp
> +#include "fuzzuf/algorithms/ijon/shared_data.hpp"
fixed

2022-06-09 08:32 UTC, Fadis commented on include/fuzzuf/executor/ijon_executor_interface.hpp
> +  /// @returnIJON feedback.
fixed

2022-06-09 08:33 UTC, Fadis commented on cmake/FindFuzzufCC.cmake
> +  find_program( FUZZUF_CC_AFL_CXX fuzzuf-afl-c++ NO_DEFAULT_PATH PATHS ${FUZZUF_CC_ROOT}/ ${FUZZUF_CC_ROOT}/bin/ )
fixed

2022-06-10 03:58 UTC, mkYYY approved these changes
Approving the PR
- [x] The reviewer understands how this PR addresses the issue and the specific changes.
- [x] This PR uses the best possible issue resolution that the reviewer can think of.
- [x] This PR is ready to be merged.

2022-06-10 03:59 UTC, merged